### ISSUE TITLE
Configure static files

### ISSUE THREAD

**Issue by CodeConnoisseur74** [CodeConnoisseur74/gloss#35]
## Acceptance Criteria:

 - Add static folder
 - Add css and js folders

___
## Tasks:
 - [x] Add static folder
 - [x] Add css and js folders
 - [x] Update settings.py
